config/routes.rb
Rails.application.routes.draw do
  get '/products/scholarship' => 'product/scholarship#index', as: 'scholarship_product'
  
  namespace :scholarship do
    resources :programs do
      resources :iterations, only: [:index, :new]
    end
    
    resources :teams do
      resources :members, controller: 'team_memberships', only: [:index, :new]
    end
    
    resources :team_memberships, only: [:create, :edit, :update, :destroy] do
      collection do
        get :with_state
      end
      
      member do
        put :accept
        put :deny
        put :change_roles
      end
    end
    
    resources :iterations, only: [:create, :show, :edit, :update, :destroy] do
      resources :participants, controller: 'iteration_participations', only: [:index, :new]
    end
    
    resources :iteration_participations, only: [:create, :edit, :update, :destroy] do
      collection do
        get :with_state
      end
      
      member do
        put :accept
        put :deny
        put :change_roles
      end
    end
    
    get 'workflow' => 'workflow#index', as: :workflow
    
    namespace 'workflow' do
      resources :organization_owner, only: :index
      resources :team_leader, only: :index
    end
  end
  
  resources :organizations do
    namespace :scholarship do
      resources :programs, only: [:index, :new]
    end
  end
end

app/controllers/scholarship/workflow/organization_owner_controller.rb
class Scholarship::Workflow::OrganizationOwnerController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @iteration_participations = Scholarship::IterationParticipation.of_organization_owner(current_user).requested.
    order_by_user_full_name.includes(iteration: { program: :organization}).paginate(page: params[:page], per_page: 25) 
  end
end

app/controllers/scholarship/workflow/team_leader_controller.rb
class Scholarship::Workflow::TeamLeaderController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @team_memberships = Scholarship::TeamMembership.of_team_leader(current_user).requested.
    order_by_user_full_name.includes(:team).paginate(page: params[:page], per_page: 25) 
  end
end

app/controllers/scholarship/workflow_controller.rb
class Scholarship::WorkflowController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @twitter_sidenav_level = 2
    @sidenav_links_count = 1
  end
end

app/views/scholarship/workflow/organization_owner/index.html.erb
<h3><%= t('scholarship_iteration_participations.workflow.title') %></h3>
<div class="tabs">
	<ul>
	  <li><a href="#requested_team_memberships"><%= t('scholarship_iteration_participations.workflow.requested') %></a></li>
	  <li>
	  	<a href="<%= with_state_scholarship_iteration_participations_path(state: 'accepted') %>">
	  		<%= t('scholarship_iteration_participations.workflow.accepted') %>
	    </a>
	  </li>
	  <li>
	  	<a href="<%= with_state_scholarship_iteration_participations_path(state: 'changed_roles') %>">
	  		<%= t('scholarship_iteration_participations.workflow.changed_roles') %>
	    </a>
	  </li>
	  <li>
	  	<a href="<%= with_state_scholarship_iteration_participations_path(state: 'denied') %>">
	  		<%= t('scholarship_iteration_participations.workflow.denied') %>
	    </a>
	  </li>
	</ul>
	<div id="requested_team_memberships">
		<%= render 'scholarship/iteration_participations/collection', locals: { show_team: true } %>
	</div>
</div>