config/routes.rb
Rails.application.routes.draw do
  get '/products/scholarship' => 'product/scholarship#index', as: 'scholarship_product'
  
  namespace :scholarship do
    resources :programs do
      resources :iterations, only: [:index, :new]
    end
    
    resources :teams do
      resources :members, controller: 'team_memberships', only: [:index, :new]
    end
    
    resources :team_memberships, only: [:create, :edit, :update, :destroy] do
      collection do
        get :with_state
      end
      
      member do
        put :accept
        put :deny
        put :change_roles
      end
    end
    
    resources :iterations, only: [:create, :show, :edit, :update, :destroy] do
      resources :participants, controller: 'iteration_participations', only: [:index, :new]
    end
    
    resources :iteration_participations, only: [:create, :edit, :update, :destroy] do
      collection do
        get :with_state
      end
      
      member do
        put :accept
        put :deny
        put :change_roles
      end
    end
    
    get 'workflow' => 'workflow#index', as: :workflow
    
    namespace 'workflow' do
      resources :organization_owner, only: :index
      resources :team_leader, only: :index
    end
  end
  
  resources :organizations do
    namespace :scholarship do
      resources :programs, only: [:index, :new]
    end
  end
end

app/models/concerns/scholarship/role_request.rb
module Scholarship
  module RoleRequest
    extend ActiveSupport::Concern
  
    included do
      const_set 'EVENTS', [:accept, :deny, :change_roles]
      
      scope :order_by_user_full_name, -> do 
        joins(:user).
        select(table_name + ".*, CONCAT(users.first_name, ' ', users.last_name) AS user_full_name").
        order('user_full_name ASC')
      end
      
      scope :requested, -> { where(state: 'requested') }
      scope :accepted, -> { where(state: 'accepted') }
      scope :denied, -> { where(state: 'denied') }
      scope :changed_roles, -> { where(state: 'changed_roles') }
      
      validates :roles, presence: true
      
      after_initialize :set_initial_state
      
      state_machine :state, initial: :requested do
        event :accept do
          transition [:requested, :denied, :changed_roles] => :accepted
        end
        
        event :deny do
          transition [:requested, :accepted] => :denied
        end
        
        event :change_roles do
          transition :accepted => :changed_roles
        end
      end
      
      private
      
      def set_initial_state
        self.state ||= :requested
      end
    end
  end
end

app/models/product/scholarship.rb
class Product::Scholarship < ::Product
end

app/models/scholarship/iteration.rb
module Scholarship
  class Iteration < ActiveRecord::Base
    self.table_name = 'scholarship_iterations'
    
    include Applicat::Mvc::Model::Resource::Base
    
    belongs_to :program, class_name: 'Scholarship::Program'
    
    has_many :participations, class_name: 'Scholarship::IterationParticipation'
    has_many :participants, class_name: 'User', through: :participations
    
    validates :program_id, presence: true, uniqueness: { scope: [:from, :to] }
    validates :from, presence: true
    validates :to, presence: true
    validate :to_must_be_greater_than_from
    
    attr_accessible :name, :program_id, :from, :to
    
    PARENT_TYPES = ['scholarship_program']
    
    def to_s
      name.present? ? name : "#{program.name} #{from.strftime('%d.%m.%Y')} - #{to.strftime('%d.%m.%Y')}"
    end
    
    private
    
    def to_must_be_greater_than_from
      if from > to
        errors.add(
          :to,
          I18n.t('activerecord.errors.models.scholarship_iteration.attributes.to.to_must_be_greater_than_from')
        )
      end
    end
  end
end

app/models/scholarship/program.rb
module Scholarship
  class Program < ActiveRecord::Base
    self.table_name = 'scholarship_programs'
    
    include Applicat::Mvc::Model::Resource::Base
    
    belongs_to :organization

    has_many :iterations, class_name: 'Scholarship::Iteration', dependent: :destroy
    
    validates :organization_id, presence: true
    validates :name, presence: true, uniqueness: { scope: [:organization_id] }
    
    attr_accessible :name, :text, :organization_id
    
    PARENT_TYPES = ['organization']
  end
end

app/models/scholarship/team.rb
module Scholarship
  class Team < ActiveRecord::Base
    KINDS = %w(sponsored voluntary)
    
    self.table_name = 'scholarship_teams'
    
    include Applicat::Mvc::Model::Resource::Base
    
    has_many :memberships, class_name: 'Scholarship::TeamMembership'
    has_many :members, class_name: 'User', through: :memberships, source: 'user'
    
    validates :name, presence: true, uniqueness: true
    validates :kind, presence: true, inclusion: { in: KINDS }
    
    attr_accessible :name, :text, :kind, :github_handle, :twitter_handle
    
    attr_accessor :leader
    
    after_create :create_team_leader_membership
    
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    private
    
    def create_team_leader_membership
      membership = memberships.new(roles: [:team_leader])
      membership.user_id = leader.try(:id)
      membership.save!
      membership.accept!
    end
  end
end

app/controllers/concerns/scholarship/base_controller.rb
module Scholarship
  module BaseController
    extend ActiveSupport::Concern
      
    def application_navigation
      :main_scholarship
    end
    
    def navigation_product_path
      scholarship_product_path
    end
    
    def navigation_product_name
      'Scholarship'
    end
  end
end

app/controllers/product/scholarship_controller.rb
class Product::ScholarshipController < ApplicationController
  include ::Scholarship::BaseController
  
  def index
  end
end

app/controllers/scholarship/iteration_participations_controller.rb
class Scholarship::IterationParticipationsController < ApplicationController
  include ::Scholarship::BaseController
  include Applicat::Mvc::Controller::Resource
  include VoluntaryScholarship::IterationParticipationsHelper
  
  transition_actions Scholarship::IterationParticipation::EVENTS
  
  before_filter :find_iteration_participation, only: [:new]
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def index
    @iteration = Scholarship::Iteration.find(params[:iteration_id])
    @program = @iteration.program
    @iteration_participations = @iteration.participations.accepted.order_by_user_full_name.paginate(page: params[:page], per_page: 25)
  end
  
  def new
  end
  
  def create
    @iteration_participation = Scholarship::IterationParticipation.new(params[:scholarship_iteration_participation])
    @iteration_participation.user = current_user
    @iteration = @iteration_participation.iteration
    @program = @iteration.program
    
    if @iteration_participation.save
      redirect_to scholarship_iteration_participants_path(@iteration_participation.iteration), notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if params[:scholarship_iteration_participation][:roles].present? && !can_update_scholarship_iteration_participation_roles?(@iteration_participation)
      raise CanCan::AccessDenied  
    end
    
    if @iteration_participation.update_attributes(params[:scholarship_iteration_participation])
      redirect_to [:edit, @iteration_participation], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @iteration_participation.destroy
    redirect_to scholarship_iteration_participants_path(@iteration_participation.iteration), notice: t('general.form.destroyed')
  end
  
  def resource
    @iteration_participation
  end
  
  def with_state
    @iteration_participations = Scholarship::IterationParticipation.of_organization_owner(current_user).send(params[:state]).
    order_by_user_full_name.includes(iteration: { program: :organization}).paginate(page: params[:page], per_page: 25) 
    render layout: false
  end
  
  private
  
  def find_iteration_participation
    @iteration_participation = case action_name
    when 'new'
      @iteration = Scholarship::Iteration.find(params[:iteration_id])
      @program = @iteration.program
      @iteration.participations.new
    end
  end
  
  def not_found
    redirect_to root_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/scholarship/iterations_controller.rb
class Scholarship::IterationsController < ApplicationController
  include ::Scholarship::BaseController
  include Applicat::Mvc::Controller::Resource
  
  before_filter :find_iteration, only: [:new]
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def index
    @program = Scholarship::Program.find(params[:program_id])
    @iterations = @program.iterations.paginate(page: params[:page], per_page: 25).order('scholarship_iterations.from DESC') 
  end
  
  def show
    @program = @iteration.program
  end
  
  def new
  end
  
  def create
    @iteration = Scholarship::Iteration.new(params[:scholarship_iteration])
    
    if @iteration.save
      redirect_to @iteration, notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @iteration.update_attributes(params[:scholarship_iteration])
      redirect_to @iteration, notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @iteration.destroy
    redirect_to scholarship_program_iterations_path(@iteration.program), notice: t('general.form.destroyed')
  end
  
  def resource
    @iteration
  end
  
  protected
  
  def set_twitter_sidenav_level
    @twitter_sidenav_level = 5
  end
  
  private
  
  def find_iteration
    @iteration = case action_name
    when 'new'
      @program = Scholarship::Program.find(params[:program_id])
      @program.iterations.new
    end
  end
  
  def not_found
    redirect_to root_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/scholarship/programs_controller.rb
class Scholarship::ProgramsController < ApplicationController
  include ::Scholarship::BaseController
  include Applicat::Mvc::Controller::Resource
  
  before_filter :find_program, only: [:new]  
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def index
    @organization = find_parent Scholarship::Program::PARENT_TYPES
    @programs = @organization ? @organization.scholarship_programs.order(:name) : Scholarship::Program.order(:name)
    @programs = @programs.paginate(page: params[:page], per_page: 25)
  end
  
  def show
  end
  
  def new
  end
  
  def create
    @program = Scholarship::Program.new(params[:scholarship_program])
    
    if @program.save
      redirect_to @program, notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @program.update_attributes(params[:scholarship_program])
      redirect_to @program, notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @program.destroy
    redirect_to organization_scholarship_programs_path(@program.organization), notice: t('general.form.destroyed')
  end
  
  def resource
    @program
  end
  
  private
  
  def find_program
    @program = case action_name
    when 'new' then 
      @organization = Organization.friendly.find(params[:organization_id]) if params[:organization_id].present?
      @organization.present? ? @organization.scholarship_programs.new : Scholarship::Program.new
    end
  end
  
  def not_found
    redirect_to scholarship_programs_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/scholarship/team_memberships_controller.rb
class Scholarship::TeamMembershipsController < ApplicationController
  include ::Scholarship::BaseController
  include Applicat::Mvc::Controller::Resource
  include VoluntaryScholarship::TeamMembershipsHelper
  
  transition_actions Scholarship::TeamMembership::EVENTS
  
  before_filter :find_team_membership, only: [:new]
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def index
    @team = Scholarship::Team.friendly.find(params[:team_id])
    @team_memberships = @team.memberships.accepted.order_by_user_full_name.paginate(page: params[:page], per_page: 25)
  end
  
  def new
  end
  
  def create
    @team_membership = Scholarship::TeamMembership.new(params[:scholarship_team_membership])
    @team_membership.user = current_user
    @team = @team_membership.team
    
    if @team_membership.save
      redirect_to scholarship_team_members_path(@team_membership.team), notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if params[:scholarship_team_membership][:roles].present? && !can_update_scholarship_team_membership_roles?(@team_membership)
      raise CanCan::AccessDenied  
    end
    
    if @team_membership.update_attributes(params[:scholarship_team_membership])
      redirect_to [:edit, @team_membership], notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @team_membership.destroy
    redirect_to scholarship_team_members_path(@team_membership.team), notice: t('general.form.destroyed')
  end
  
  def resource
    @team_membership
  end
  
  def with_state
    @team_memberships = Scholarship::TeamMembership.of_team_leader(current_user).send(params[:state]).
    order_by_user_full_name.includes(:team).paginate(page: params[:page], per_page: 25) 
    render layout: false
  end
  
  private
  
  def find_team_membership
    @team_membership = case action_name
    when 'new'
      @team = Scholarship::Team.friendly.find(params[:team_id])
      @team.memberships.new
    end
  end
  
  def not_found
    redirect_to root_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/scholarship/teams_controller.rb
class Scholarship::TeamsController < ApplicationController
  include ::Scholarship::BaseController
  include Applicat::Mvc::Controller::Resource
  
  before_filter :find_team, only: [:show, :edit, :update, :destroy]  
  
  load_and_authorize_resource
  
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
  def index
    @teams = Scholarship::Team.order(:name)
    @teams = @teams.paginate(page: params[:page], per_page: 25)
  end
  
  def show
  end
  
  def new
    @team = Scholarship::Team.new(kind: 'sponsored')
  end
  
  def create
    @team = Scholarship::Team.new(params[:scholarship_team])
    @team.leader = current_user
    
    if @team.save
      redirect_to @team, notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @team.update_attributes(params[:scholarship_team])
      redirect_to @team, notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to scholarship_teams_path, notice: t('general.form.destroyed')
  end
  
  def resource
    @team
  end
  
  private
  
  def find_team
    @team = Scholarship::Team.friendly.find(params[:id])
  end
  
  def not_found
    redirect_to scholarship_teams_path, notice: t('general.exceptions.not_found')
  end
end

app/controllers/scholarship/workflow/organization_owner_controller.rb
class Scholarship::Workflow::OrganizationOwnerController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @iteration_participations = Scholarship::IterationParticipation.of_organization_owner(current_user).requested.
    order_by_user_full_name.includes(iteration: { program: :organization}).paginate(page: params[:page], per_page: 25) 
  end
end

app/controllers/scholarship/workflow/team_leader_controller.rb
class Scholarship::Workflow::TeamLeaderController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @team_memberships = Scholarship::TeamMembership.of_team_leader(current_user).requested.
    order_by_user_full_name.includes(:team).paginate(page: params[:page], per_page: 25) 
  end
end

app/controllers/scholarship/workflow_controller.rb
class Scholarship::WorkflowController < ApplicationController
  include ::Scholarship::BaseController
  
  before_filter :authenticate_user!
  
  def index
    @twitter_sidenav_level = 2
    @sidenav_links_count = 1
  end
end

app/helpers/voluntary_scholarship/iteration_participations_helper.rb
module VoluntaryScholarship
  module IterationParticipationsHelper
    def can_update_scholarship_iteration_participation_roles?(iteration_participation)
      return false unless user_signed_in?
      
      iteration_participation.new_record? || 
      current_user.is_master? || 
      current_user.id == iteration_participation.iteration.program.organization.user_id ||
      (can?(:update, iteration_participation) && iteration_participation.accepted?)
    end
    
    def destroy_scholarship_iteration_participation_link(iteration_participation)
      link_to(
        t('scholarship_iteration_participations.destroy.title'), 
        scholarship_iteration_participation_path(iteration_participation.id), id: "iteration_participation_#{iteration_participation.id}", method: :delete, 
        data: { confirm: t('general.questions.are_you_sure') },
        onclick: "delete_link('iteration_participation_#{iteration_participation.id}'); return false;"
      )
    end
  end
end

app/views/scholarship/iteration_participations/_actions.html.erb
<% if can?(:destroy, iteration_participation) || can?(:edit, iteration_participation) %>
<div class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= t('general.actions') %></a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
  <% if can? :destroy, iteration_participation %>    
    <li><%= destroy_scholarship_iteration_participation_link(iteration_participation) %></li>
  <% end %>
  <% if can? :edit, iteration_participation %>    
    <li><%= link_to t('general.edit'), eval("edit_scholarship_iteration_participation_path(iteration_participation)") %></li>
  <% end %>
  
  <% links = event_links_for_resource(iteration_participation, 'scholarship_iteration_participations') %>
  <% if links.any? %>
  <li class="divider"></li>
  <%= render 'shared/resource/event_elements', links: links %>
  <% end %>
  </ul>
</div>
<% end %>

app/views/scholarship/iteration_participations/_collection.html.erb
<% show_iteration ||= false %>
<% if @iteration_participations.none? || @iteration_participations.select{|e| e.id.present? }.none? %>
<p><%= I18n.t("scholarship_iteration_participations.index.empty_collection")%></p>
<% else %>
<table class="table table-striped">
  <thead>
    <tr class="<%= cycle('odd', 'even') %>">
      <th><%= t('activerecord.models.user') %></th>
  <% if show_iteration %>
      <th><%= t('activerecord.models.scholarship/organization') %></th>
      <th><%= t('activerecord.models.scholarship/iteration') %></th>
  <% end %>
      <th><%= t('attributes.roles') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @iteration_participations.select{|e| e.id.present? }.each do |iteration_participation| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td>
        <%= link_to iteration_participation.user.full_name, user_path(iteration_participation.user) %>
      </td>
    <% if show_iteration %> 
      <td>
      	<%= link_to iteration_participation.iteration.program.organization, organization_path(iteration_participation.iteration.program.organization) %>
      </td>
      <td>
      	<%= link_to iteration_participation.iteration, scholarship_iteration_path(iteration_participation.iteration) %>
      </td>
    <% end %>
      <td>
      	<%= iteration_participation.roles.map(&:to_s).map(&:humanize).join(', ') %>
      </td>
      <td>
      	<%= render partial: 'scholarship/iteration_participations/actions', locals: { iteration_participation: iteration_participation } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<%= will_paginate @iteration_participations %>

<% if @iteration.present? && user_signed_in? %>
	<% if current_user && current_user.is_participant_of_scholarship_iteration?(@iteration) %>
	  <%= destroy_scholarship_iteration_participation_link(current_user.participation_of_scholarship_iteration(@iteration)) %>
	<% elsif can?(:create, Scholarship::IterationParticipation) %>
	  <%= link_to t("scholarship_iteration_participations.new.title"), new_scholarship_iteration_participant_path(@iteration) %>
	<% end %>
<% end %>

app/views/scholarship/iteration_participations/_form.html.erb
<%= simple_form_for(@iteration_participation, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
  <%= f.input :iteration_id, as: :hidden %>
  <%= render partial: 'shared/form/error_messages', locals: { resource: @iteration_participation } %>
  
	<%= f.input :team_id, collection: current_user.scholarship_teams %>
	<% if can_update_scholarship_iteration_participation_roles?(@iteration_participation) %>
	  <%= f.input :roles, as: :check_boxes, collection: Scholarship::IterationParticipation::ROLES.map { |r| [r.capitalize, r] }, include_hidden: false, label: t('attributes.roles') %>
  <% else %>
    <%= render partial: 'shared/layouts/twitter_bootstrap/control_group', locals: { 
      required: true, label: t('attributes.roles'),
      field: @iteration_participation.roles.map(&:to_s).map(&:humanize).join(', ')
    } %>
  <% end %>
  <%= f.input :text, label: t('attributes.text'), input_html: {style: 'width: 500px; height:300px;'} %>
  
  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/scholarship/iteration_participations/edit.html.erb
<h3><%= t('scholarship_iteration_participations.edit.title') %></h3>

<%= render 'form' %>

app/views/scholarship/iteration_participations/index.html.erb
<h3><%= t("scholarship_iteration_participations.index.title") %></h3>

<%= render 'collection' %>

app/views/scholarship/iteration_participations/new.html.erb
<h3><%= t('scholarship_iteration_participations.new.title') %></h3>

<%= render 'form' %>

app/views/scholarship/iteration_participations/with_state.html.erb
<%= render partial: 'collection', locals: { show_iteration: true } %>